service: omni-crm
provider:
  stackTags:
    DeployedBY: BizCloudExperts
    Application: Microsoft-dynamics
    Environment: ${self:provider.stage}
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - "ses:*"
        - s3:PutObject
        - s3:GetObject
     Resource: '*'
  
functions:
- ${file(functions/seslambda.yml)}

resources:
- ${file(resources/s3bucket.yml)}
- ${file(resources/lambda-permissions.yml)}
- ${file(resources/bucket-policy.yml)}
- ${file(resources/ses-ruleset-name.yml)}
- ${file(resources/ses.yml)}






