service: omni-crm
provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
   - Effect: "Allow"
     Action:
        - "ses:*"
        - s3:PutObject
        - s3:GetObject
     Resource: '*'
functions:
    seslambda:
        timeout: 300
        handler: dynamics-crm-prod.lambda_handler
        environment:
            BUCKET: !Ref S3Bucket

resources:
- ${file(resources/lambda-permissions.yml)}
- ${file(resources/s3bucket.yml)}
- ${file(resources/bucket-policy.yml)}
- ${file(resources/ses-ruleset-name.yml)}
- ${file(resources/ses.yml)}






