Resources:
        BucketPolicy:
            Type: AWS::S3::BucketPolicy
            Properties: 
                Bucket: 
                    Ref: S3Bucket
                PolicyDocument: 
                    Statement: 
                        - 
                            Action: 
                                - "s3:PutObject"
                            Effect: "Allow"
                            Resource: 
                                Fn::Join: 
                                    - ""
                                    - 
                                        - "arn:aws:s3:::"
                                        - omni-crm
                                        - "/*"
                            Principal: "*"
                            Condition: 
                                StringEquals: 
                                    aws:Referer: 
                                        - "535687408418"